version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: KARTVERKET
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  karverket-app:
    image: ${DOCKER_REGISTRY-}karverket
    build:
      context: .
      dockerfile: /Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      ConnectionStrings__DefaultConnection: "Server=mariadb;Database=KARTVERKET;User=root;Password=1234;"
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend: